### ISSUE TITLE
Verify length & special characters in uploading form

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#12]
![image](https://user-images.githubusercontent.com/3889245/39188847-16a4ce00-47d1-11e8-91e9-e61ddf2445eb.png)

**Comment by DomantasP** [comment]
Most probably we are not going to do any kind of validation on these field because: 
1. We can never be sure what is valid and what is not. Maybe user will use some kind of symbols that actually make sense and make data more understandable.
2. After dataset is submitted it must be confirmed manually, so we are going to filter all the invalid datasets by hand.

We are loving your feedback, keep up the good work. We place these issues on our git project board, so you can track the progress.

**Comment by dyoann** [comment]
Ok if you verify manually that makes sense!
Maybe just put a max length just in case then

**Comment by dyoann** [comment]
I’ll do more feedback as soon as I see progress :)
