### ISSUE TITLE
Why is there no update on the month of April???

### ISSUE THREAD

**Issue by cyrilbensonyu** [AigangNetwork/aigang-platform-web#14]
We need an update. Did you exit scam? We'll report to FBI and Interpol if you did. No communication on Telegram, Twitter or Reddit? Kindly fix this issue or else I'll post that this is a dead coin on all reddit community.

**Comment by cyrilbensonyu** [comment]
@galisamas @dariusdev @DomantasP @Maxpeinas @llavre

**Comment by dariusdev** [comment]
Hi @cyrilbensonyu, 

these issues registering functionality is used for our platform impovements, bugs and clear stuctured requests for change something. 

If you are unhappy and want to blame someone this project is not for you and nobody is waitting you here. You can sell your coins where you want, write messages where you want, and do what you want, because this is a free world. 

If you are waitting marketing update about product you should wait until it will be released. It is strategic decision when these messeges should be released. 

Regarding this issue and for more easier development process tracking our deveopment team decided to release new repository with fast links here:
[https://aigangnetwork.github.io/](https://aigangnetwork.github.io/) 

and Team sprint reviews will be available here:
[https://github.com/AigangNetwork/aigangnetwork.github.io/wiki](https://github.com/AigangNetwork/aigangnetwork.github.io/wiki) 

Thank you for your understanding and we wish you best luck.

**Comment by cyrilbensonyu** [comment]
@dariusdev on your twitter and reddit account people think that your project is dead because your team is not communication. no update for the past month!!!!! this will go down to zero.
