### ISSUE TITLE
(many) Label sync issue when back in upload / re-upload

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#17]
When clicking on "Back" after uploading a dataset, we get that screen (which is normal so far):
![image](https://user-images.githubusercontent.com/3889245/39511261-1b3250b0-4ded-11e8-9d7d-7322a219cebe.png)

1)
However, we can still click on continue, and it shows the previously  uploaded dataset 
(So I guess the form is not reset, in this case, it could be  useful to say that the file is still "active")

2)
The info shown after clicking on continue are the one from the previous dataset (so it's active)

3)
When we click back, choose a new dataset, then continue , we can still see the old values (of the first uploading attempt of a dataset), indeed  the tilte and description are filled 

![image](https://user-images.githubusercontent.com/3889245/39511402-a4793ae6-4ded-11e8-96b6-35e93691f157.png)

**Comment by adasiunas** [comment]
Yes, when you click back old file is still uploaded, we added an additional label "File attached" to inform the user that file is still there.

Regarding old Dataset title and description. It should not refresh when a new file or remote access point is provided because title and description are general information. (Imagine a scenario, when user provides brief description about the dataset and notices that he provided incorrect file, perhaps he would like to change file without any impact on Description/Title (only on structure))
