### ISSUE TITLE
Dataset that are awaiting for approval are accessible (easily)

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#18]
If we check the code we can see the link of disabled dataset :

![image](https://user-images.githubusercontent.com/3889245/39511533-144b79ba-4dee-11e8-9256-bf0ddc35da6d.png)

We can verify it's accessible (it shouldn't be I suppose ...) 
https://testplatform.aigang.network/data/0711097f0c454ffeb777411330e3cb2f/

**Comment by dyoann** [comment]
And I checked,  you can also add models to them (before approval)

**Comment by DomantasP** [comment]
I changed "/forbidden" route to "/access-denied" just to be a little bit more clear and easier to understand. All pages that are not accessible to the user will redirect to this page.

"/data/2b6e482338504b0fa7f1d5bcf3874e02/edit" was a wrong route, it was actually "/data/edit/2b6e482338504b0fa7f1d5bcf3874e02" and that's why you were getting redirected to "page is not available". But now I changed it to "/data/2b6e482338504b0fa7f1d5bcf3874e02/edit" just to be consistent with the models and more intuitive.

I couldn't reproduce "Forbidden" alert dialog "/data/0711097f0c454ffeb777411330e3cb2f/" when trying to reach a dataset that hasn't been approved yet. I think you might have tested it before one of the updates we rolled a bit later. However if you will keep getting this problem, please reopen this issue.

**Comment by dyoann** [comment]
@DomantasP Now it's showing "Access denied", so I guess  it has been fixed 👍
