### ISSUE TITLE
[BUG] On file upload user are able to drag and drop other files not only .csv

### ISSUE THREAD

**Issue by DomantasP** [AigangNetwork/aigang-platform-web#4]
-fix dont allow to take other extension files in UI
-check uploading error message "Bad File content Tyoe" to more detailed description

Founder: dyoann

**Comment by dyoann** [comment]
![image](https://user-images.githubusercontent.com/3889245/39187537-dff7a560-47cd-11e8-86e3-dc53270aaf73.png)

Should also check that if the extension is .csv then the file is not garbage :-)
I uploaded a mp4 renamed csv and it worked 😀

**Comment by adasiunas** [comment]
Ofcourse it would work, csv file is a text file and no matter what file you convert to the text file our platform UI will accept it. However, you wouldn't be able to upload it. Currently we can not validate the 10MB file if it's content is csv based because it might slow down application performance.

**Comment by dyoann** [comment]
What I meant is it shouldn’t work because the header of an mp4 file is obviously not a CSV . It should not show the page with incompatible fake CSV !

**Comment by dyoann** [comment]
We shouldn't have this following result 
(here I simply renamed a <10 png to csv), the interface is broken then: 

![image](https://user-images.githubusercontent.com/3889245/39514777-7ed06886-4df8-11e8-9400-b55e0eedcc02.png)

( Also "All Files" could be removed from the Drop Files, and only CSV should be shown)
